# Generated by Django 5.0.1 on 2024-01-19 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HTTPWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='\n        Makes reading and addressing steps easier.\n        Not possible to have multiple steps within a http workflow with the same name.\n        ', max_length=255)),
                ('ordering', models.PositiveSmallIntegerField(help_text="\n        Steps in a http workflow, will get executed in an'\n        ascending order according to the value of this field.\n        Not possible to have multiple steps within a http workflow with the same ordering.\n        ")),
                ('http_workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='http_workflow.httpworkflow')),
            ],
            options={
                'unique_together': {('name', 'http_workflow'), ('ordering', 'http_workflow')},
            },
        ),
        migrations.CreateModel(
            name='HTTPRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('post', 'Post')], max_length=10)),
                ('body', models.JSONField(blank=True, null=True)),
                ('url', models.URLField()),
                ('status', models.PositiveSmallIntegerField(help_text='Contains the response.status_code, if this record has benn executed at least once', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('step', models.ForeignKey(help_text='\n        Belongs to this step, this record gets executed in parallel among other\n        http request which belong to the same step\n        ', on_delete=django.db.models.deletion.CASCADE, to='http_workflow.step')),
            ],
        ),
    ]
